package liraz.paletlang.generators;

import liraz.paletlang.model.DesignSystem;
import liraz.paletlang.model.DesignSystem.*;
import liraz.paletlang.util.HexColor;
import liraz.paletlang.util.Strings;

import java.util.List;

/**
 * Gera o design system como variáveis CSS (custom properties) dentro de um único
 * bloco {@code :root}, permitindo que qualquer stylesheet consuma os tokens via
 * {@code var(--...)}. A opção {@code prefix} (padrão {@code --pl-}) adiciona um
 * namespace a cada propriedade, e {@code file} define o nome do arquivo de saída
 * (padrão {@code tokens.css}).
 */
public final class CssGenerator implements Generator {

    @Override public String targetName() { return "css"; }

    @Override
    public List<GeneratedFile> generate(DesignSystem ds, Target target) {
        String prefix = normalizePrefix(optString(target, "prefix", "--pl-"));
        String file = optString(target, "file", "tokens.css");

        StringBuilder css = new StringBuilder();
        String name = ds.metaValue("name");

        css.append("/*\n * Design tokens generated by PaletLang");

        if (name != null)
            css.append(" from \"").append(name).append('"');

        String version = ds.metaValue("version");

        if (version != null)
            css.append(" v").append(version);

        css.append("\n * Do not edit by hand. If necessary, regenerate from the .paletlang source.\n */\n");

        css.append(":root {\n");

        if (!ds.colors.isEmpty()) {
            css.append("  /* colors */\n");
            for (Color c : ds.colors)
                css.append(prop(prefix + "color-" + Strings.slug(c.name()), HexColor.parse(c.hex()).toHex()));

            for (Color c : ds.colors)
                if (c.hasRole())
                    css.append(prop(prefix + "role-" + Strings.slug(c.role()),
                            "var(" + prefix + "color-" + Strings.slug(c.name()) + ")"));
        }

        if (!ds.fonts.isEmpty()) {
            css.append("\n  /* typography families */\n");
            for (Font f : ds.fonts) {
                css.append(prop(prefix + "font-" + Strings.slug(f.name()), Strings.cssFontFamily(f.family())));

                if (f.hasWeight())
                    css.append(prop(prefix + "font-" + Strings.slug(f.name()) + "-weight", String.valueOf(f.weight())));
            }
        }

        if (!ds.scale.isEmpty()) {
            css.append("\n  /* typography scale */\n");
            for (ScaleStep s : ds.scale) {
                css.append(prop(prefix + "text-" + Strings.slug(s.name()), Strings.num(s.size()) + "px"));

                if (s.hasLineHeight())
                    css.append(prop(prefix + "leading-" + Strings.slug(s.name()), Strings.num(s.lineHeight())));
            }
        }

        if (!ds.spacingTokens.isEmpty()) {
            css.append("\n  /* spacing */\n");
            if (ds.spacingBase != null)
                css.append(prop(prefix + "space-base", Strings.num(ds.spacingBase) + "px"));

            for (SpacingToken t : ds.spacingTokens)
                css.append(prop(prefix + "space-" + Strings.slug(t.name()), Strings.num(ds.spacingPx(t)) + "px"));
        }

        css.append("}\n");
        return List.of(new GeneratedFile(file, css.toString()));
    }

    private static String prop(String name, String value) {
        return "  " + name + ": " + value + ";\n";
    }

    private static String normalizePrefix(String prefix) {
        String p = prefix == null || prefix.isBlank() ? "--pl-" : prefix.trim();
        if (!p.startsWith("--")) p = "--" + p;
        return p;
    }

    private static String optString(Target t, String key, String fallback) {
        Opt o = t.option(key);
        return o != null && o.value().kind() == Kind.STRING ? o.value().text() : fallback;
    }
}
